### ISSUE TITLE
MC question display not working in student view

### ISSUE THREAD

**Issue by patudom** [cosmicds/educator_dashboard#61]
Somewhere along the way it looks like we broke the MC question display in the student view. (When you click a row in the table, the question does not display, and there are a bunch of errors in the terminal).
<img width="1487" alt="Screen Shot 2023-10-18 at 4 46 33 PM" src="https://github.com/cosmicds/educator_dashboard/assets/12750048/bd5ce76c-077d-4af9-af8e-89e0c7bd82e5">

```
ERROR:    Uncaught exception: Traceback (most recent call last):
  File "/Users/Pat/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/ipywidgets/widgets/widget.py", line 206, in __call__
    local_value = callback(*args, **kwargs)
  File "/Users/Pat/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py", line 60, in _handle_event
    getattr(self, "vue_" + event)(data)
  File "/Users/Pat/Documents/GitHub/educator_dashboard/educator_dashboard/components/TableComponents/jldatatable.py", line 69, in vue_on_click
    self.callbacks[0].on_click(data)
  File "/Users/Pat/Documents/GitHub/educator_dashboard/educator_dashboard/components/TableComponents/jldatatable.py", line 115, in on_click
    on_row_click(data)
  File "/Users/Pat/Documents/GitHub/educator_dashboard/educator_dashboard/components/MultipleChoice.py", line 146, in row_action
    qjson = Query.get_question(key)
TypeError: get_question() missing 1 required positional argument: 'question_tag'
```

**Comment by johnarban** [comment]
I believe this can be closed. This has been fixed in #65
